---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "commercial-paper-network"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "The Commercial Paper network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# list of participating organizations in this network
#
organizations:
  Org1:
    mspid: magnetocorpMSP

    peers:
      - peer1.magnetocorp.example.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - camagnetocorp

  Org2:
    mspid: digibankMSP
    peers:
      - peer5.digibank.example.com
    certificateAuthorities:
      - camagnetocorp



#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer1.magnetocorp.example.com:
    # this URL is used to send endorsement and query requests
    url: grpc://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer1.magnetocorp.example.com
      request-timeout: 120001

  peer5.digibank.example.com:
    url: grpc://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer5.digibank.example.com
      request-timeout: 120001

# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  camagnetocorp:
    url: http://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
        enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: camagnetocorp

  cadigibank:
    url: http://localhost:8054
    httpOptions:
      verify: false
    registrar:
        enrollId: admin
        enrollSecret: adminpw
    caName: cadigibank
